export const myProjects = [
  {
    title: 'Evitar fadiga',
    description: 'Projeto desenvolvido no nlw4 da rocketseat. A cada x segundos o desenvolvedor tem umas missões como: "tampar os olhos por 3 minutos". Ao concluir a missão, o mesmo ganhar XP para passar de nível.',
    tecnologies: ['Next', 'JavaScript', 'CSS'],
    src: 'https://user-images.githubusercontent.com/47106171/109422549-c8857700-79ba-11eb-9e17-ced561d6db46.gif',
    git: 'https://github.com/joaochioda/nlw4',
  },
  {
    title: 'Podcast player',
    description: 'Projeto desenvolvido no nlw5 da rocketseat. O projeto é um player online de podcasts da rocketseat. ',
    tecnologies: ['React', 'JavaScript', 'CSS'],
    src: 'https://user-images.githubusercontent.com/47106171/115886285-236da480-a427-11eb-945d-a5e8a590d05b.gif',
    git: 'https://github.com/joaochioda/nlw5',
  },
  {
    title: 'Quizz',
    description: 'Projeto desenvolvido no nlw5 da rocketseat. O projeto é um mini quizz feito em flutter com login com google e integrações com firebase.',
    tecnologies: ['Flutter'],
    src: 'https://user-images.githubusercontent.com/47106171/116007542-9f621b00-a5e6-11eb-9043-fb51c05d5fe9.gif',
    git: 'https://github.com/joaochioda/nlw5-flutter',
  },
  {
    title: 'Chat online',
    description: 'Projeto desenvolvido no nlw6 da rocketseat. O projeto permite que o usuário crie uma sala e faça perguntas. Também foi feito login com google e integração com firebase para salvar o chat.',
    tecnologies: ['React', 'JavaScript', 'CSS'],
    src: 'https://user-images.githubusercontent.com/47106171/123350262-fcb81100-d530-11eb-990a-ad2a4afd4cd4.gif',
    git: 'https://github.com/joaochioda/nlw6-react',
  },
  {
    title: 'Super Calculadora',
    description: 'Projeto desenvolvido no bootcamp da IGTI. O objetivo era desenvolver uma super calculadora utlizando apenas HTML e JavaScript.',
    tecnologies: ['JavaScript', 'HTML', 'CSS'],
    src: 'https://user-images.githubusercontent.com/47106171/93672386-d7b5df80-fa80-11ea-99ff-5630ae111400.gif',
    git: 'https://github.com/joaochioda/igti-bootcamp-front',
  },
  {
    title: 'Filtro de pessoas',
    description: 'Projeto desenvolvido no bootcamp da IGTI. O objetivo era desenvolver um filtro de pessoas com as informações vindas de um backend.',
    tecnologies: ['JavaScript', 'HTML', 'CSS'],
    src: 'https://user-images.githubusercontent.com/47106171/94351450-f68f1580-002e-11eb-910a-b34a44086001.gif',
    git: 'https://github.com/joaochioda/igti-bootcamp-front',
  },
  {
    title: 'Mini Twitter',
    description: 'Projeto desenvolvido no bootcamp da IGTI. O objetivo era criar um CRUD do twitter e salvar em um banco local.',
    tecnologies: ['React', 'CSS'],
    src: 'https://user-images.githubusercontent.com/47106171/97115475-b70f2400-16d5-11eb-9386-729de754c5d5.gif',
    git: 'https://github.com/joaochioda/igti-bootcamp-front',
  },
  {
    title: 'Mini Instagram',
    description: 'Projeto desenvolvido no bootcamp da IGTI. Dado um conjunto de dados vindo de um banco local, ser possível visualizar os posts da pessoa selecionada.',
    tecnologies: ['React', 'CSS'],
    src: 'https://user-images.githubusercontent.com/47106171/99158436-8b1e0780-26b1-11eb-9802-8d26356a2f07.gif',
    git: 'https://github.com/joaochioda/igti-bootcamp-front',
  },
  {
    title: 'FogZone',
    description: 'Projeto desenvolvido como modelo de negócios para o TCC. Ao logar com sua conta do google, o usuário pode favoritar essencias, buscar por informações e até fazer comentários pertinentes.',
    tecnologies: ['Spring', 'Flutter'],
    src: 'https://user-images.githubusercontent.com/47106171/94488292-bf4c7000-01b8-11eb-9471-bb0a252c8469.PNG',
    git: 'https://github.com/joaochioda/tccZone',
  },
  {
    title: 'Cadastro de aulas',
    description: 'Projeto desenvolvido no bootcamp da Rocketseat. Este projeto tem como objetivo axuliar os professores a cadastrarem suas aulas e os preços de cada uma. Toda interação no front esta integrado com o backend feito em Node e o banco usado foi o postgres.',
    tecnologies: ['React', 'Node', 'CSS', 'Postgres'],
    src: 'https://user-images.githubusercontent.com/47106171/94367802-487b7e00-00b7-11eb-8da9-7af176d17d3d.gif',
    git: 'https://github.com/joaochioda/rockttutorial',
  },
  {
    title: 'Cadastro de orfanatos',
    description: 'Projeto desenvolvido no bootcamp da Rocketseat. Este projeto tem como objetivo cadastrar orfanatos utilizando api de maps, salvar as imagens e as informações em um banco de dados postgres. Para o backend foi utilizado Node.',
    tecnologies: ['React', 'Node', 'CSS', 'Postgres'],
    src: 'https://user-images.githubusercontent.com/47106171/99466472-3bdb0f80-291b-11eb-9353-96a5c22b6fdd.gif',
    git: 'https://github.com/joaochioda/NLW3 ',
  },
  {
    title: 'Leitor de mensagens',
    description: 'Ao logar com a conta do google, é possível ler as mensagem que foram enviadas no portifólio. É possível marcar elas como lidas e até excluí-las se necessário. Foi utilizado o realtime database do Firebase.',
    tecnologies: ['ReactNative', 'CSS'],
    src: 'https://user-images.githubusercontent.com/47106171/101490930-cffc2d80-3941-11eb-9324-46afaa8dcf97.gif',
    git: 'https://github.com/joaochioda/see-mails-mobile',
  },
  {
    title: 'Treinando Css',
    description: 'Projeto pessoal para treinar css. A cada dia é feito um mini projetinho.',
    tecnologies: ['HTML', 'CSS'],
    src: 'https://user-images.githubusercontent.com/47106171/99467951-34693580-291e-11eb-9528-410ff77f33f9.gif',
    git: 'https://github.com/joaochioda/30days-effects-css',
  },
];
